ground-x/caver-js-ext-kas

index.js
src/kas/kas.js

This PR introduces adding comments

Added comments

---

TERMS-OF-USE.md

This PR introduces adding TERMS-OF-USE.md file.

Added terms of use

---

.circleci/config.yml

- Change publish logic test before deploy major version(same as rc publish)
- remove stage_qa since it not use alpha version

Add test steps before publish production

---

TERMS-OF-USE.md

This PR modify KAS hompage url in TERMS_OF_USE.md

modify KAS hompage url.

---

TERMS-OF-USE.md

This PR introduces modification few words in terms of use file

Modified few with terms of use

---

package.json
webpack.config.js

This PR introduces new webpack config file.
I created webpack.config.js file separately to define more options.

Modified webpack config to remove build warning

---

.circleci/config.yml

- Add test context when it test, it contains KAS credential, Klaytn address for baobab 

[CIRCLECI] add context for test job

---

.gitignore
README.md
package.json
test/intTest/anchorIntTest.js
test/intTest/tokenHistoryIntTest.js
test/intTest/walletIntTest.js
test/nodeAPI/testNodeAPI.js
test/testEnv.js
test/testUtils.js

This PR introduces set test environment variables from `process.env`.
For `npm run testDev` which run test script with `--dev`flag, i defined environment variables locally to test in dev env. (for running test in local)
So, there are two methods to run test locally
1. Modify `test/testEnv.json`
2. create `.env` and define environment values
If this is a relatively large or complex change, kick off the discussion by …

Modified test environment

---

src/rest-client/src/tokenHistory/model/TransferItem.js
test/intTest/tokenHistoryIntTest.js

This PR introduces adding branch logic in TransferItem class depends on transferType.

Added branch logic depends on transferType in TransferItem

---

package.json
test/intTest/tokenHistoryIntTest.js
yamlFormatting.sh

This PR introduces draft version of formatting yaml file shell script file for generating jsDoc correctly.
You can run `npm run lintFix` to format and lint

Updated yaml formatting file

---

jsdoc.json
package.json

This PR introduces jsdoc.json configutation file.
Also i added docdash(jsdoc template) and jsdoc to package.json

Added jsdoc.json configuration file

---

.gitignore

This PR introduces adding `out` directory to `.gitignore` file.
This will be removed after docs working done.

Added out directory to gitignore for working

---

src/rest-client/src/ApiClient.js

This PR introduces modification class name from `exports` to `ApiClient`

Formatted apiclient file

---

package.json

This PR introduces new script for generating docs

Separated generate docs script

---

src/rest-client/src/tokenHistory/model/NftTransfer.js
src/rest-client/src/tokenHistory/model/TransferItem.js
src/rest-client/src/wallet/model/EventLog.js
src/rest-client/src/wallet/model/FDTransactionResult.js
src/rest-client/src/wallet/model/TransactionReceipt.js
src/rest-client/src/wallet/model/TransactionResult.js
src/rest-client/src/wallet/model/TxData.js
yamlFormatting.sh

This PR introduces modification yaml formatting shell script for model class comments.

Fixed bug for model comment bug

---

.circleci/config.yml

- Add docs update by CI when rc, production release

[CIRCLECI] Add docs update job

---

package.json

This PR introduces version upgrade to v1.0.1
After this, i will test version naming policy test with @whoisxx 

Version upgrade to 1.0.1

---

README.md

This PR introduces adding caver-java-ext-kas api reference link in README.md

Added caver-java-ext-kas api ref docs url in readme

---

package.json

This PR introduces using latest caver-js version

Updated caver-js version

---

test/intTest/kasWalletIntTest.js

This RP introduces integration test for KASWallet.

Implemented integration test for kas wallet

---

README.md

This PR introduces modification title in README.md

Modified title in readme

---

yamlFormatting.sh

This PR introduces formatting empty brace for model classes.
This logic is exited for Api classes, so i copied them.

Formatting empty brace for model classes

---

src/kas/wallet/wallet.js

This PR introduces adding getter of newly added apis in wallet.

Added getter for new apis in wallet

---

test/intTest/tokenHistoryIntTest.js

This PR introduces integration test for token history new api functions in KAS v1.1

Implemented integration test code for token history in kas 1.1

---

test/intTest/kip17IntTest.js

This PR introduces integration test code for KIP17 API
I will uncomment after KIP17 API release

Kip17 integration test codes

---

package.json

This PR introduces version update to 1.1.0

Version update to 1.1.0

---

yamls/kip17/kip17_20210113.yaml
yamls/kip17/kip17_20210113.yaml-SwaggerYaml.yaml

This PR introduces adding KIP17 api yaml files

Added yaml files for KIP17 api

---

test/intTest/kip17IntTest.js
test/intTest/tokenHistoryIntTest.js
test/intTest/walletIntTest.js

This PR introduces uncommented integration tests for KAS Wallet API, KAS Token History API and KIP-17 API v1.1

Uncommented integration test code for KAS v1.1 features

---

yamlFormatting.sh

This PR introduces when format rest-client code, get class name from file name.

Get class name from file name

---

src/kas/tokenHistory/tokenHistory.js
test/tokenHistory/testTokenHistoryAPI.js

This PR introduces adding handling for token id in number type

Added handling for number type token id

---

src/kas/kip17/kip17.js
src/kas/tokenHistory/tokenHistory.js
src/kas/wallet/wallet.js

This PR introduces adding example for caver-js-ext-kas v1.1.0 features.

Added description for api reference doc

---

README.md
test/testEnv.js

This PR introduces use private key for js separately.

Used separate sender private key for javascript

---

test/intTest/tokenHistoryIntTest.js

This PR introduces uncommenting integration test for token history api.

Uncommented integration test

---

package.json
src/wallet/kasWallet.js

This PR introduces modification of import string to absolute path.

Modified require string to absolute path

---

test/intTest/tokenHistoryIntTest.js

This PR introduces adding `tokenOwnerAddress` in tokenHistory integration test code.
Also unused code was removed.

Added tokenOwnerAddress variable in testVariables and removed unused code

---

jsdoc.json

This PR introduces adding configuration to support header link in jsDoc

Added configuration for md link support

---

TERMS-OF-USE.md

This PR introduces modification of company name

Modified company name from ground1 to groundx

---

test/intTest/kasWalletIntTest.js

This PR introduces check error code instead of message.

Check error code instead of message

---

package.json

This PR introduces update caver-js version to v1.6.1-rc.1 and caver-js-ext-kas version to v1.1.2 (to release rc version)

Update dependency for fixing vulnerabilities and caver-js-ext-kas version

---

.github/CODEOWNERS

This PR introduces adding denver as a code owner

Added code owner

---

package.json

This PR introduces update caver-js version.

Update caver-js version

---

package.json

This PR introduces fixing vulnerabilities

Updated lodash package version to fix vulnerabilities

---

src/rest-client/src/index.js
src/rest-client/src/wallet/api/FeepayerApi.js
src/rest-client/src/wallet/model/KeyStatus.js
src/rest-client/src/wallet/model/TxData.js

This PR introduces appliance of latest wallet yaml files.
Among the client codes created from latest yaml changes, only the newly added function in the Key API and the Fee Payer API have been added.

Added fee payer api and new key api function

---

src/kas/kip17/kip17.js
src/kas/tokenHistory/tokenHistoryQueryOptions.js

This PR introduces fixing mistypo

Fixed mistypo

---

yamls/kip7/kip7_20210511.yaml
yamls/kip7/kip7_20210511.yaml-SwaggerYaml.yaml

This PR introduces adding KIP-7 API yaml file

Added KIP-7 API yaml file

---

src/kas/wallet/wallet.js
test/intTest/walletIntTest.js
test/wallet/testFeePayerAPI.js
test/wallet/testKeyAPI.js

This PR introduces implementation of fee payer api.
Also key deletion function in key api of the wallet api is added.

Implemented fee payer api and new function in key api

---

src/rest-client/src/kip7/model/DeployKip7ContractRequest.js
yamls/kip7/kip7_20210517.yaml
yamls/kip7/kip7_20210517.yaml-SwaggerYaml.yaml

This PR introduces appliance of latest KIP7 API yaml file.
The `caver.kas.kip7` logic is not chagned.

Applied latest KIP7 yaml file

---

package.json

This PR introduces version update to v1.4.0

Version upgrade to 1.4.0

---

src/kas/tokenHistory/tokenHistory.js

This PR introduces fixing mistypo

Fixed mistypo in jsdoc

---

package.json

This PR introduces version up of caver-js and also version upgrade for caver-js-ext-kas to v1.4.1

Version upgrade caver-js and caver-js-ext-kas

---

.eslintignore
.eslintrc.js
.gitignore
codeGenerator/config.json
codeGenerator/generate_anchor.sh
codeGenerator/generate_kip17.sh
codeGenerator/generate_kip7.sh
codeGenerator/generate_th.sh
codeGenerator/generate_wallet.sh

This PR introduces adding code generator shell script for KAS API.
I copied script from caver-java-ext-kas :) !

Added codegenerator for each api

---

codeGenerator/config.json
codeGenerator/generate_anchor.sh
codeGenerator/generate_client_code.sh
codeGenerator/generate_kip17.sh
codeGenerator/generate_kip37.sh
codeGenerator/generate_kip7.sh
codeGenerator/generate_th.sh
codeGenerator/generate_tokenHistory.sh
codeGenerator/generate_wallet.sh
importToRequire.sh
yamlFormatting.sh

This PR introduces modification of client-code generation script.

Modified client code generation script

---

package-lock.json
package.json

This PR introduces update caver-js version

Updated libraries

---

test/intTest/tokenHistoryIntTest.js

This PR introduces modification of test code to let other people do test with their environment variables.
For now range value used for testing is fixed, so if someone wants to test with integration test code, test will be failed.

Modified test code

---

src/kas/kip37/kip37.js

This PR introduces modification of KIP-37 example and added validation logic for address.

Modified example and added validation for address

---

test/intTest/kip37IntTest.js
test/testUtils.js

This PR introduces KIP-37 integration tests.

Implemented KIP-37 integration test

---

src/kas/kas.js
src/kas/kip17/kip17.js
src/kas/kip17/kip17FeePayerOptions.js
src/rest-client/src/index.js
src/rest-client/src/kip17/model/DeployKip17ContractRequest.js
src/rest-client/src/kip17/model/Kip17ContractInfoResponse.js
src/rest-client/src/kip17/model/Kip17ContractListResponseItem.js
src/rest-client/src/kip17/model/Kip17DeployResponse.js
src/rest-client/src/kip17/model/Kip17FeePayerOptions.js
src/rest-client/src/kip17/model/Kip17FeePayerOptionsUserFeePayer.js
src/rest-client/src/kip17/model/UpdateKip17ContractRequest.js
test/intTest/kip17IntTest.js
test/intTest/kip37IntTest.js
test/intTest/kip7IntTest.js
test/kip17/testKIP17API.js
test/testUtils.js
yamls/kip17/2021-09-30-openapi-versioned.yaml

This PR introduces implementation of new KIP-17 functions.
Also i added some test util function to avoid duplicated logic.

Implemented newly added KIP-17 functions

---

src/rest-client/src/index.js
src/rest-client/src/kip37/model/DeployKip37ContractRequest.js
src/rest-client/src/kip37/model/ImportKip37ContractRequest.js
src/rest-client/src/kip37/model/Kip37Contract.js
src/rest-client/src/kip37/model/Kip37DeployResponse.js
src/rest-client/src/kip37/model/Kip37FeePayerOptions.js
src/rest-client/src/kip37/model/Kip37FeePayerOptionsResponse.js
src/rest-client/src/kip37/model/Kip37FeePayerOptionsUserFeePayer.js
src/rest-client/src/kip37/model/UpdateKip37ContractRequest.js
src/rest-client/src/kip7/model/DeployKip7ContractRequest.js
src/rest-client/src/kip7/model/Kip7ContractListResponseItem.js
src/rest-client/src/kip7/model/Kip7ContractMetadataResponse.js
src/rest-client/src/kip7/model/Kip7DeployResponse.js
src/rest-client/src/kip7/model/Kip7FeePayerOptions.js
src/rest-client/src/kip7/model/Kip7FeePayerOptionsResponse.js
src/rest-client/src/kip7/model/Kip7FeePayerOptionsResponseUserFeePayer.js
src/rest-client/src/kip7/model/UpdateKip7ContractRequest.js
yamlFormatting.sh
yamls/kip37/2021-09-30-openapi-versioned.yaml
yamls/kip7/2021-09-30-openapi-versioned.yaml

This PR introduces appliance of latest KIP-7 and KIP-37 client code.
Also i modified to check import statement more correctly in yamlFormatting script.

Applied latest yaml client code for KIP-37 and KIP-7

---

README.md
package-lock.json
package.json

This PR introduces updating README.md file and version to v1.9.0

Updated readme file and pacakge.json version

---

index.js

This PR introduces modification production url

Changed production url
